---
- name: Unseal Vault
  hosts: localhost
  gather_facts: no
  vars:
    vault_addr: "https://192.168.86.21:8200"
    # These would typically be stored securely and provided at runtime
    # Only using 3 of the 5 keys needed for unsealing
    unseal_keys:
      - "RNuIUM2IM0Lt6wH6Rk+lfdtOCHZZD/1MYEe7TFqfblkY"
      - "QGj87Zk1NyAmJMMQGPTKAClBbbnw8l3UcRbJZJPxUdEZ"
      - "crb26BZsoDOKXqnrL7NivQJWb1GdSpzsSjLqpJ1J5XbH"

  tasks:
    - name: Unseal Vault with key shares
      uri:
        url: "{{ vault_addr }}/v1/sys/unseal"
        method: POST
        body_format: json
        body:
          key: "{{ item }}"
#        status_code: 200
      register: unseal_result
      loop: "{{ unseal_keys }}"

    - name: Show Vault status
      uri:
        url: "{{ vault_addr }}/v1/sys/seal-status"
        method: GET
        status_code: 200
      register: status_result

    - name: Display final unseal status
      debug:
        var: status_result.json
