---
# tasks file for elasticsearch

- name: Installation tasks
  block:
    - name: Download and install Elasticsearch GPG key
      shell: |
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
      args:
        creates: /usr/share/keyrings/elasticsearch-keyring.gpg

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Add Elasticsearch repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: elastic-8.x

    - name: Install Elasticsearch and Kibana packages
      apt:
        name:
          - kibana
          - unzip
        state: present
        update_cache: yes

    - name: Install Elasticsearch package
      apt:
        name:
          - elasticsearch
        state: present
        update_cache: yes
      register: elastic_install

    - name: Extract elastic password from installation output
      set_fact:
        elastic_password: "{{ elastic_install.stdout_lines | select('regex', 'elastic built-in superuser is :') | first | regex_replace('^.*is : (.*)$', '\\1') }}"
      when: elastic_install.changed

    - name: Display elastic password
      debug:
        msg: "Elastic user password: ⭐ {{ elastic_password }} ⭐"
      when: elastic_install.changed
#TASK [elasticsearch : Display full Elasticsearch installation output] ********************************************************************************
#ok: [ns-elastic-01] => {
#    "msg": "stdout: ['Reading package lists...', 'Building dependency tree...', 'Reading state information...', 'The following NEW packages will be installed:', '  elasticsearch', '0 upgraded, 1 newly installed, 0 to remove and 29 not upgraded.', 'Need to get 636 MB of archives.', 'After this operation, 1210 MB of additional disk space will be used.', 'Get:1 https://artifacts.elastic.co/packages/8.x/apt stable/main amd64 elasticsearch amd64 8.17.1 [636 MB]', 'Fetched 636 MB in 27s (23.4 MB/s)', 'Selecting previously unselected package elasticsearch.', '(Reading database ... ', '(Reading database ... 5%', '(Reading database ... 10%', '(Reading database ... 15%', '(Reading database ... 20%', '(Reading database ... 25%', '(Reading database ... 30%', '(Reading database ... 35%', '(Reading database ... 40%', '(Reading database ... 45%', '(Reading database ... 50%', '(Reading database ... 55%', '(Reading database ... 60%', '(Reading database ... 65%', '(Reading database ... 70%', '(Reading database ... 75%', '(Reading database ... 80%', '(Reading database ... 85%', '(Reading database ... 90%', '(Reading database ... 95%', '(Reading database ... 100%', '(Reading database ... 177744 files and directories currently installed.)', 'Preparing to unpack .../elasticsearch_8.17.1_amd64.deb ...', 'Creating elasticsearch group... OK', 'Creating elasticsearch user... OK', 'Unpacking elasticsearch (8.17.1) ...', 'Setting up elasticsearch (8.17.1) ...', '--------------------------- Security autoconfiguration information ------------------------------', '', 'Authentication and authorization are enabled.', 'TLS for the transport and HTTP layers is enabled and configured.', '', 'The generated password for the elastic built-in superuser is : UZdLDhGsTvsEEYg+1ZWc', '', 'If this node should join an existing cluster, you can reconfigure this with', \"'/usr/share/elasticsearch/bin/elasticsearch-reconfigure-node --enrollment-token <token-here>'\", 'after creating an enrollment token on your existing cluster.', '', 'You can complete the following actions at any time:', '', 'Reset the password of the elastic built-in superuser with ', \"'/usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic'.\", '', 'Generate an enrollment token for Kibana instances with ', \" '/usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana'.\", '', 'Generate an enrollment token for Elasticsearch nodes with ', \"'/usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s node'.\", '', '-------------------------------------------------------------------------------------------------', '### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd', ' sudo systemctl daemon-reload', ' sudo systemctl enable elasticsearch.service', '### You can start elasticsearch service by executing', ' sudo systemctl start elasticsearch.service', 'NEEDRESTART-VER: 3.5', 'NEEDRESTART-KCUR: 5.15.0-131-generic', 'NEEDRESTART-KEXP: 5.15.0-131-generic', 'NEEDRESTART-KSTA: 1']\nstderr: []\n"
#}



    - name: Configure Elasticsearch service state
      systemd:
        name: elasticsearch
        enabled: yes
        state: stopped
  tags:
    - installation

- name: Configuration tasks
  block:
    - name: Ensure Elasticsearch is stopped before configuration
      systemd:
        name: elasticsearch
        state: stopped
  tags:
    - configure

- name: Certificate rotation tasks
  block:
    - name: Ensure Elasticsearch is stopped before rotating certificates
      systemd:
        name: elasticsearch
        state: stopped
  tags:
    - rotate-certs
