---
# tasks file for elasticsearch

- name: Installation tasks
  block:
    - name: Download and install Elasticsearch GPG key
      shell: |
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
      args:
        creates: /usr/share/keyrings/elasticsearch-keyring.gpg

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Add Elasticsearch repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: elastic-8.x

    - name: Install Elasticsearch and Kibana packages
      apt:
        name:
          - kibana
          - unzip
        state: present
        update_cache: yes

    - name: Install Elasticsearch - Note the elastic user password
      apt:
        name:
          - elasticsearch
        state: present
        update_cache: yes
      register: elastic_install

    - name: Enable Elasticsearch service
      systemd:
        name: elasticsearch
        enabled: yes
        state: stopped

    - name: Extract elastic password from installation output
      set_fact:
        elastic_password: "{{ elastic_install.stderr | regex_search('The generated password for the elastic built-in superuser is : (.+)$', '\\1') | first }}"
      when: elastic_install.changed

    - name: Display elastic password
      debug:
        msg: "Elastic superuser password: {{ elastic_password }}"
      when: elastic_install.changed
  tags:
    - installation

- name: Configuration tasks
  block:
    - name: Ensure Elasticsearch is stopped before configuration
      systemd:
        name: elasticsearch
        state: stopped
  tags:
    - configure

- name: Certificate rotation tasks
  block:
    - name: Ensure Elasticsearch is stopped before rotating certificates
      systemd:
        name: elasticsearch
        state: stopped
  tags:
    - rotate-certs
