---
# tasks file for elasticsearch

- name: Installation tasks
  block:
    - name: Download and install Elasticsearch GPG key
      shell: |
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
      args:
        creates: /usr/share/keyrings/elasticsearch-keyring.gpg

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Add Elasticsearch repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: elastic-8.x

    - name: Install Elasticsearch and Kibana packages
      apt:
        name:
          - kibana
          - unzip
        state: present
        update_cache: yes

    - name: Install Elasticsearch package
      apt:
        name:
          - elasticsearch
        state: present
        update_cache: yes
      register: elastic_install

    - name: Display full Elasticsearch installation output
      debug:
        msg: |
          stdout: {{ elastic_install.stdout_lines | default([]) }}
          stderr: {{ elastic_install.stderr_lines | default([]) }}
      when: elastic_install.changed

    - name: Configure Elasticsearch service state
      systemd:
        name: elasticsearch
        enabled: yes
        state: stopped
  tags:
    - installation

- name: Configuration tasks
  block:
    - name: Ensure Elasticsearch is stopped before configuration
      systemd:
        name: elasticsearch
        state: stopped
  tags:
    - configure

- name: Certificate rotation tasks
  block:
    - name: Ensure Elasticsearch is stopped before rotating certificates
      systemd:
        name: elasticsearch
        state: stopped
  tags:
    - rotate-certs
